POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIxMiIsImlkIjoiNjNmMTQ2MzU0M2M3MmQ4YTBlZDRkZmUyIiwiaWF0IjoxNjc2NzU2NjQwLCJleHAiOjE2NzY3NjAyNDB9.4YXUtpStQxz1LPYPYfzU4IBXTkSJLaNC5TD7M-eLZLI

{
    "title": "blogi3668884",
    "author": "thk",
    "url": "url",
    "likes": 2
}